// react-hooks-todo/src/component/ComList.js
import React from 'react'

function ComList(props) {
  const { list, setComplated, removeItem } = props
  
  return (
    <div>
      {
        list.map((item,index) => {
          return (
            <div key={ index }>
              <input
                type="checkbox"
                checked={ item.complated }
                onChange={ () => setComplated(item.id) }
              />
              <span style={{textDecoration: item.complated ? 'line-through' : '', padding: '2px 8px'  }}>{ item.content }</span>
              <button onClick={ () => removeItem(item.id) }>删除</button>
            </div>
          )
        })
      }
    </div>
  )
}

export default ComList

// vue2-todo/src/components/ComList.vue
<template>
  <div>
    <div
      v-for="(item, index) of list"
      :key="index"
    >
      <input type="checkbox" :checked="item.complated" @click="setComplated(item.id)">
      <span :style="{ 'text-decoration': item.complated ? 'line-through':'' }">{{item.content}}</span>
      <button @click="onRemoveItem(item.id)">删除</button>
    </div>
  </div>
</template>

<script>
export default ({
  name: 'ComList',
  props: {
    list: Array
  },
  methods: {
    onRemoveItem(id) {
      this.$emit('onRemoveItem', id)
    },
    setComplated(id) {
      this.$emit('setComplated', id)
    }
  }
})
</script>

<style lang="scss" scoped></style>
