// vue2-todo/src/components/ComAdd.vue
<template>
  <div>
    <input type="text" v-model="inputValue" placeholder="添加新项">
    <button @click="onAddItem">添加</button>
  </div>
</template>

<script>
export default ({
  name: 'ComAdd',
  data () {
    return {
      inputValue: ''
    }
  },
  methods: {
    onAddItem() {
      let _value = this.inputValue
      _value = _value.trim()
      if (!_value) return

      this.$emit("set-add-item", {
        id: new Date().getTime(),
        content: _value,
        complated: false
      })

      this.inputValue = ''
    }
  }
})
</script>

<style lang="scss" scoped></style>

// react-hooks-todo/src/component/ComAdd.js
import React, { useRef } from 'react'

function ComAdd(props) {
  const inputValue = useRef()
  // 从props中获取父组件传递的事件,父子组件事件/属性传递
  const { addItem } = props

  const onAddItem = () => {
    const value = inputValue.current.value.trim()
    if (!value) return

    addItem({
      id: new Date().getTime(),
      content: value,
      complated: false
    })

    inputValue.current.value = ''
  }

  return (
    <div>
      <input ref={ inputValue } type="text" placeholder="新选项" />
      <button onClick={ onAddItem }>添加</button>
    </div>
  )
}

export default ComAdd
