// vue3-todo/src/components/ComAdd.vue
<template>
  <div class="add-box">
    <input type="text" v-model="inputValue" placeholder="新选项">
    <button class="add-btn" @click="setAddItem">添加</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

export default defineComponent({
  name: 'ComAdd',
  setup(props, { emit }) {
    const inputValue = ref('')
    
    const setAddItem = () => {
      const _value = inputValue.value.trim()
      if (!_value) return

      emit('set-add-item', {
        id: new Date().getTime(),
        content: _value,
        complated: false
      })

      inputValue.value = ''
    }
    
    return {
      inputValue,
      setAddItem  
    }
  }
})
</script>

// react-hooks-todo/src/component/ComAdd.js
import React, { useRef } from 'react'

function ComAdd(props) {
  const inputValue = useRef()
  // 从props中获取父组件传递的事件,父子组件事件/属性传递
  const { addItem } = props

  const onAddItem = () => {
    const value = inputValue.current.value.trim()
    if (!value) return

    addItem({
      id: new Date().getTime(),
      content: value,
      complated: false
    })

    inputValue.current.value = ''
  }

  return (
    <div>
      <input ref={ inputValue } type="text" placeholder="新选项" />
      <button onClick={ onAddItem }>添加</button>
    </div>
  )
}

export default ComAdd
