// react-hooks-todo/src/component/ComList.js
import React from 'react'

function ComList(props) {
  const { list, setComplated, removeItem } = props
  
  return (
    <div>
      {
        list.map((item,index) => {
          return (
            <div key={ index }>
              <input
                type="checkbox"
                checked={ item.complated }
                onChange={ () => setComplated(item.id) }
              />
              <span style={{textDecoration: item.complated ? 'line-through' : '', padding: '2px 8px'  }}>{ item.content }</span>
              <button onClick={ () => removeItem(item.id) }>删除</button>
            </div>
          )
        })
      }
    </div>
  )
}

export default ComList

// vue3-todo/src/components/ComList.vue
<template>
  <div>
    <div v-for="(item, index) in list" :key="index">
      <input type="checkbox" :checked="item.complated" @click="setComplated(item.id)">
      <span :style="{ 'text-decoration': item.complated ? 'line-through' : '' }">{{item.content}}</span>
      <button @click="removeItem(item.id)">删除</button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: '',
  props: {
    list: Array
  },
  setup(props, { emit }) {
    const setComplated = (id: number) => {
      emit('set-complated', id)
    }

    const removeItem = (id: number) => {
      emit('remove-item', id)
    }

    return {
      setComplated,
      removeItem
    }
  }
})
</script>

<style lang="scss" scoped></style>
