// react-hooks-todo/src/App.js
import React, { useState, useCallback } from 'react'
import ComAdd from './component/ComAdd'
import ComList from './component/ComList'

function App() {
  const [todoList, setTodoList]  = useState([])

  const onAddItem = useCallback((newItem) => {
    setTodoList(todoList => [newItem, ...todoList])
  }, [])

  const onRemoveItem = useCallback((id) => {
    setTodoList(todoList => {
      return todoList.filter(item => item.id !== id)
    })
  }, [])

  const onSetComplated = useCallback((id) => {
    setTodoList(todoList => {
      return todoList.map(item => {
        if (item.id === id) {
          item.complated = !item.complated
        }
        return item
      })
    })
  }, [])

  return (
    <div className="App">
      <ComAdd addItem={ onAddItem } />
      <ComList
        list={ todoList }
        removeItem={ onRemoveItem }
        setComplated={onSetComplated }
      />
    </div>
  );
}

export default App;

// vue3-todo/src/App.vue
<template>
  <div>
    <com-add class="com-add" @setAddItem="setAddItem" />
    <com-list :list="list" @setComplated="setComplated" @removeItem="removeItem" />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import ComAdd from './components/ComAdd.vue'
import ComList from './components/ComList.vue'

export default defineComponent({
  name: 'App',
  components: {
    ComAdd,
    ComList
  },
  props: {
    list: Array
  },
  setup() {
    type ItemType = {
      id: number,
      content: string,
      complated: boolean
    }

    const list = ref(Array<ItemType>())

    const setAddItem = (params: ItemType) => {
      list.value.push(params)
    }

    const setComplated = (id: number) => {
      list.value.map(item => {
        if (item.id === id) {
          item.complated = !item.complated
        }
        return item
      })
    }

    const removeItem = (id: number) => {
      list.value = list.value.filter(item => item.id !== id)
    }

    return {
      list,
      setAddItem,
      setComplated,
      removeItem
    }
  }
});
</script>

<style>
.com-add > .add-btn {
  color: red;
}
</style>
